/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as dashboardRouteRouteImport } from './routes/(dashboard)/route'
import { Route as dashboardIndexRouteImport } from './routes/(dashboard)/index'
import { Route as dashboardProductsRouteImport } from './routes/(dashboard)/products'
import { Route as dashboardComponentsRouteImport } from './routes/(dashboard)/components'
import { Route as dashboardCategoriesRouteImport } from './routes/(dashboard)/categories'
import { Route as dashboardBranchesRouteImport } from './routes/(dashboard)/branches'
import { Route as dashboardProductsProductIdRouteImport } from './routes/(dashboard)/products.$productId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardRouteRoute = dashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardIndexRoute = dashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardProductsRoute = dashboardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardComponentsRoute = dashboardComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardCategoriesRoute = dashboardCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardBranchesRoute = dashboardBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardProductsProductIdRoute =
  dashboardProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => dashboardProductsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/branches': typeof dashboardBranchesRoute
  '/categories': typeof dashboardCategoriesRoute
  '/components': typeof dashboardComponentsRoute
  '/products': typeof dashboardProductsRouteWithChildren
  '/': typeof dashboardIndexRoute
  '/products/$productId': typeof dashboardProductsProductIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/branches': typeof dashboardBranchesRoute
  '/categories': typeof dashboardCategoriesRoute
  '/components': typeof dashboardComponentsRoute
  '/products': typeof dashboardProductsRouteWithChildren
  '/': typeof dashboardIndexRoute
  '/products/$productId': typeof dashboardProductsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(dashboard)': typeof dashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/(dashboard)/branches': typeof dashboardBranchesRoute
  '/(dashboard)/categories': typeof dashboardCategoriesRoute
  '/(dashboard)/components': typeof dashboardComponentsRoute
  '/(dashboard)/products': typeof dashboardProductsRouteWithChildren
  '/(dashboard)/': typeof dashboardIndexRoute
  '/(dashboard)/products/$productId': typeof dashboardProductsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/branches'
    | '/categories'
    | '/components'
    | '/products'
    | '/'
    | '/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/branches'
    | '/categories'
    | '/components'
    | '/products'
    | '/'
    | '/products/$productId'
  id:
    | '__root__'
    | '/(dashboard)'
    | '/login'
    | '/(dashboard)/branches'
    | '/(dashboard)/categories'
    | '/(dashboard)/components'
    | '/(dashboard)/products'
    | '/(dashboard)/'
    | '/(dashboard)/products/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  dashboardRouteRoute: typeof dashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)': {
      id: '/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/': {
      id: '/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/products': {
      id: '/(dashboard)/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof dashboardProductsRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/components': {
      id: '/(dashboard)/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof dashboardComponentsRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/categories': {
      id: '/(dashboard)/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof dashboardCategoriesRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/branches': {
      id: '/(dashboard)/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof dashboardBranchesRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/products/$productId': {
      id: '/(dashboard)/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof dashboardProductsProductIdRouteImport
      parentRoute: typeof dashboardProductsRoute
    }
  }
}

interface dashboardProductsRouteChildren {
  dashboardProductsProductIdRoute: typeof dashboardProductsProductIdRoute
}

const dashboardProductsRouteChildren: dashboardProductsRouteChildren = {
  dashboardProductsProductIdRoute: dashboardProductsProductIdRoute,
}

const dashboardProductsRouteWithChildren =
  dashboardProductsRoute._addFileChildren(dashboardProductsRouteChildren)

interface dashboardRouteRouteChildren {
  dashboardBranchesRoute: typeof dashboardBranchesRoute
  dashboardCategoriesRoute: typeof dashboardCategoriesRoute
  dashboardComponentsRoute: typeof dashboardComponentsRoute
  dashboardProductsRoute: typeof dashboardProductsRouteWithChildren
  dashboardIndexRoute: typeof dashboardIndexRoute
}

const dashboardRouteRouteChildren: dashboardRouteRouteChildren = {
  dashboardBranchesRoute: dashboardBranchesRoute,
  dashboardCategoriesRoute: dashboardCategoriesRoute,
  dashboardComponentsRoute: dashboardComponentsRoute,
  dashboardProductsRoute: dashboardProductsRouteWithChildren,
  dashboardIndexRoute: dashboardIndexRoute,
}

const dashboardRouteRouteWithChildren = dashboardRouteRoute._addFileChildren(
  dashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  dashboardRouteRoute: dashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
